import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { DashboardLayout } from "@/components/dashboard/DashboardLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import { useCurrency } from "@/contexts/CurrencyContext";
import { Link2, Copy, TrendingUp, Users, DollarSign, Eye, Plus, CheckCircle, Pause, Play } from "lucide-react";
import { format } from "date-fns";
import { fr } from "date-fns/locale";

export default function MyAffiliations() {
  const { user } = useAuth();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const { formatPrice, currency } = useCurrency();
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Fetch user's affiliations
  const { data: affiliations, isLoading: affiliationsLoading } = useQuery({
    queryKey: ["my-affiliations", user?.id],
    queryFn: async () => {
      if (!user) return [];
      const { data, error } = await supabase
        .from("affiliations")
        .select(`
          *,
          formations (
            id,
            title,
            price,
            image_url,
            affiliation_type,
            affiliation_value
          )
        `)
        .eq("affiliate_id", user.id)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data || [];
    },
    enabled: !!user,
  });

  // Fetch available formations for affiliation
  const { data: availableFormations, isLoading: formationsLoading } = useQuery({
    queryKey: ["available-formations-for-affiliation", user?.id],
    queryFn: async () => {
      if (!user) return [];
      
      // Get formations with affiliation enabled that the user hasn't already affiliated with
      const { data: existingAffiliations } = await supabase
        .from("affiliations")
        .select("formation_id")
        .eq("affiliate_id", user.id);

      const existingFormationIds = existingAffiliations?.map(a => a.formation_id) || [];

      let query = supabase
        .from("formations")
        .select("id, title, price, image_url, affiliation_enabled, affiliation_type, affiliation_value, author_id")
        .eq("affiliation_enabled", true)
        .eq("status", "approved")
        .neq("author_id", user.id);

      if (existingFormationIds.length > 0) {
        query = query.not("id", "in", `(${existingFormationIds.join(",")})`);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data || [];
    },
    enabled: !!user,
  });

  // Create affiliation
  const createAffiliation = useMutation({
    mutationFn: async (formationId: string) => {
      if (!user) throw new Error("Non authentifié");
      
      const { data, error } = await supabase
        .from("affiliations")
        .insert({
          formation_id: formationId,
          affiliate_id: user.id,
          affiliate_code: "", // Will be generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["my-affiliations"] });
      queryClient.invalidateQueries({ queryKey: ["available-formations-for-affiliation"] });
      toast({ title: "Lien d'affiliation créé avec succès" });
    },
    onError: (error: any) => {
      toast({ 
        title: "Erreur", 
        description: error.message || "Impossible de créer le lien d'affiliation", 
        variant: "destructive" 
      });
    },
  });

  // Toggle affiliation status
  const toggleStatus = useMutation({
    mutationFn: async ({ id, status }: { id: string; status: string }) => {
      const { error } = await supabase
        .from("affiliations")
        .update({ status })
        .eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["my-affiliations"] });
      toast({ title: "Statut mis à jour" });
    },
  });

  const copyAffiliateLink = (affiliateCode: string, affiliationId: string) => {
    const baseUrl = window.location.origin;
    const link = `${baseUrl}/formations?ref=${affiliateCode}`;
    navigator.clipboard.writeText(link);
    setCopiedId(affiliationId);
    toast({ title: "Lien copié dans le presse-papiers" });
    setTimeout(() => setCopiedId(null), 2000);
  };

  const calculateCommission = (formation: any) => {
    if (!formation) return "N/A";
    if (formation.affiliation_type === "percentage") {
      const commissionAmount = Math.round(formation.price * formation.affiliation_value / 100);
      return `${formation.affiliation_value}% (${formatPrice(commissionAmount)})`;
    }
    return formatPrice(formation.affiliation_value);
  };

  const totalEarnings = affiliations?.reduce((acc, a) => acc + (a.total_earned || 0), 0) || 0;
  const totalClicks = affiliations?.reduce((acc, a) => acc + (a.clicks || 0), 0) || 0;
  const totalConversions = affiliations?.reduce((acc, a) => acc + (a.conversions || 0), 0) || 0;

  return (
    <DashboardLayout 
      title="Mes affiliations" 
      description="Gérez vos liens d'affiliation et suivez vos gains"
    >
      <div className="space-y-6">
        {/* Stats Cards */}
        <div className="grid gap-4 md:grid-cols-4">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Liens actifs</CardTitle>
              <Link2 className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                {affiliations?.filter(a => a.status === "active").length || 0}
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Clics totaux</CardTitle>
              <Eye className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{totalClicks}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Conversions</CardTitle>
              <Users className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-green-600">{totalConversions}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Gains totaux</CardTitle>
              <DollarSign className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-primary">{formatPrice(totalEarnings)}</div>
            </CardContent>
          </Card>
        </div>

        <Tabs defaultValue="my-links" className="space-y-4">
          <TabsList>
            <TabsTrigger value="my-links">Mes liens d'affiliation</TabsTrigger>
            <TabsTrigger value="available">Formations disponibles</TabsTrigger>
          </TabsList>

          <TabsContent value="my-links">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Link2 className="h-5 w-5" />
                  Mes liens d'affiliation
                </CardTitle>
                <CardDescription>
                  Partagez ces liens pour gagner des commissions sur les ventes
                </CardDescription>
              </CardHeader>
              <CardContent>
                {affiliationsLoading ? (
                  <p className="text-muted-foreground">Chargement...</p>
                ) : affiliations && affiliations.length > 0 ? (
                  <div className="overflow-x-auto">
                    <Table>
                      <TableHeader>
                        <TableRow>
                          <TableHead>Formation</TableHead>
                          <TableHead>Code</TableHead>
                          <TableHead>Commission</TableHead>
                          <TableHead>Clics</TableHead>
                          <TableHead>Conversions</TableHead>
                          <TableHead>Gains</TableHead>
                          <TableHead>Statut</TableHead>
                          <TableHead className="text-right">Actions</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {affiliations.map((affiliation: any) => (
                          <TableRow key={affiliation.id}>
                            <TableCell>
                              <div className="font-medium max-w-[200px] truncate">
                                {affiliation.formations?.title || "Formation supprimée"}
                              </div>
                            </TableCell>
                            <TableCell>
                              <code className="text-xs bg-muted px-2 py-1 rounded">
                                {affiliation.affiliate_code}
                              </code>
                            </TableCell>
                            <TableCell>
                              <span className="text-sm">
                                {calculateCommission(affiliation.formations)}
                              </span>
                            </TableCell>
                            <TableCell>{affiliation.clicks}</TableCell>
                            <TableCell>
                              <span className="text-green-600 font-medium">
                                {affiliation.conversions}
                              </span>
                            </TableCell>
                            <TableCell>
                              <span className="font-medium">
                                {formatPrice(affiliation.total_earned || 0)}
                              </span>
                            </TableCell>
                            <TableCell>
                              <Badge variant={affiliation.status === "active" ? "default" : "secondary"}>
                                {affiliation.status === "active" ? "Actif" : "Pausé"}
                              </Badge>
                            </TableCell>
                            <TableCell className="text-right">
                              <div className="flex items-center justify-end gap-2">
                                <Button
                                  variant="outline"
                                  size="sm"
                                  onClick={() => copyAffiliateLink(affiliation.affiliate_code, affiliation.id)}
                                >
                                  {copiedId === affiliation.id ? (
                                    <CheckCircle className="h-4 w-4 text-green-600" />
                                  ) : (
                                    <Copy className="h-4 w-4" />
                                  )}
                                </Button>
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => toggleStatus.mutate({
                                    id: affiliation.id,
                                    status: affiliation.status === "active" ? "paused" : "active"
                                  })}
                                >
                                  {affiliation.status === "active" ? (
                                    <Pause className="h-4 w-4" />
                                  ) : (
                                    <Play className="h-4 w-4" />
                                  )}
                                </Button>
                              </div>
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                ) : (
                  <div className="text-center py-12">
                    <Link2 className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
                    <h3 className="text-lg font-medium mb-2">Aucun lien d'affiliation</h3>
                    <p className="text-muted-foreground mb-4">
                      Consultez les formations disponibles pour créer vos premiers liens
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="available">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="h-5 w-5" />
                  Formations disponibles
                </CardTitle>
                <CardDescription>
                  Créez des liens d'affiliation pour ces formations et gagnez des commissions
                </CardDescription>
              </CardHeader>
              <CardContent>
                {formationsLoading ? (
                  <p className="text-muted-foreground">Chargement...</p>
                ) : availableFormations && availableFormations.length > 0 ? (
                  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                    {availableFormations.map((formation: any) => (
                      <Card key={formation.id} className="overflow-hidden">
                        <div className="aspect-video bg-muted flex items-center justify-center">
                          {formation.image_url ? (
                            <img 
                              src={formation.image_url} 
                              alt={formation.title}
                              className="w-full h-full object-cover"
                            />
                          ) : (
                            <TrendingUp className="h-8 w-8 text-muted-foreground" />
                          )}
                        </div>
                        <CardContent className="p-4">
                          <h4 className="font-semibold mb-2 line-clamp-2">{formation.title}</h4>
                          <div className="flex items-center justify-between mb-3">
                            <span className="text-lg font-bold text-primary">
                              {formatPrice(formation.price)}
                            </span>
                            <Badge variant="outline">
                              {formation.affiliation_type === "percentage" 
                                ? `${formation.affiliation_value}%` 
                                : formatPrice(formation.affiliation_value)}
                            </Badge>
                          </div>
                          <p className="text-sm text-muted-foreground mb-4">
                            Commission: {calculateCommission(formation)}
                          </p>
                          <Button 
                            className="w-full" 
                            onClick={() => createAffiliation.mutate(formation.id)}
                            disabled={createAffiliation.isPending}
                          >
                            <Plus className="h-4 w-4 mr-2" />
                            Devenir affilié
                          </Button>
                        </CardContent>
                      </Card>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-12">
                    <TrendingUp className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
                    <h3 className="text-lg font-medium mb-2">Aucune formation disponible</h3>
                    <p className="text-muted-foreground">
                      Il n'y a pas de formations avec affiliation active pour le moment
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </DashboardLayout>
  );
}
