import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

export interface Event {
  id: string;
  title: string;
  description: string | null;
  type: "webinar" | "in-person" | "hybrid" | "other";
  image_url: string | null;
  location: string | null;
  online_link: string | null;
  start_date: string;
  end_date: string | null;
  max_participants: number | null;
  price: number;
  is_free: boolean;
  organizer_id: string;
  status: "draft" | "published" | "cancelled" | "completed";
  created_at: string;
  updated_at: string;
  organizer?: {
    id: string;
    full_name: string | null;
    avatar_url: string | null;
  };
  registrations_count?: number;
}

export interface EventRegistration {
  id: string;
  event_id: string;
  user_id: string;
  status: "confirmed" | "cancelled" | "attended";
  payment_status: "pending" | "paid" | "refunded" | "free";
  ticket_number: string;
  registered_at: string;
  event?: Event;
}

export const useEvents = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const { data: events, isLoading } = useQuery({
    queryKey: ["events"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("events")
        .select("*")
        .eq("status", "published")
        .gte("start_date", new Date().toISOString())
        .order("start_date", { ascending: true });

      if (error) throw error;

      // Fetch organizer profiles
      const organizerIds = [...new Set((data || []).map(e => e.organizer_id))];
      const { data: profiles } = await supabase
        .from("profiles")
        .select("id, full_name, avatar_url")
        .in("id", organizerIds);

      const profilesMap = new Map((profiles || []).map(p => [p.id, p]));

      // Get registration counts
      const eventIds = (data || []).map(e => e.id);
      const { data: registrations } = await supabase
        .from("event_registrations")
        .select("event_id")
        .in("event_id", eventIds)
        .eq("status", "confirmed");

      const countMap = new Map<string, number>();
      (registrations || []).forEach(r => {
        countMap.set(r.event_id, (countMap.get(r.event_id) || 0) + 1);
      });

      return (data || []).map(event => ({
        ...event,
        organizer: profilesMap.get(event.organizer_id),
        registrations_count: countMap.get(event.id) || 0,
      })) as Event[];
    },
  });

  const registerForEvent = useMutation({
    mutationFn: async ({ eventId, isFree }: { eventId: string; isFree: boolean }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Not authenticated");

      const { data, error } = await supabase
        .from("event_registrations")
        .insert({
          event_id: eventId,
          user_id: user.id,
          payment_status: isFree ? "free" : "pending",
          ticket_number: "", // Will be generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["events"] });
      queryClient.invalidateQueries({ queryKey: ["my-registrations"] });
      toast({
        title: "Inscription réussie !",
        description: `Votre numéro de ticket : ${data.ticket_number}`,
      });
    },
    onError: (error: Error) => {
      if (error.message.includes("duplicate")) {
        toast({
          title: "Déjà inscrit",
          description: "Vous êtes déjà inscrit à cet événement",
          variant: "destructive",
        });
      } else {
        toast({
          title: "Erreur",
          description: "Impossible de s'inscrire à l'événement",
          variant: "destructive",
        });
      }
    },
  });

  return {
    events,
    isLoading,
    registerForEvent,
  };
};

export const useEventDetail = (eventId: string) => {
  return useQuery({
    queryKey: ["event", eventId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("events")
        .select("*")
        .eq("id", eventId)
        .maybeSingle();

      if (error) throw error;
      if (!data) return null;

      // Fetch organizer
      const { data: organizer } = await supabase
        .from("profiles")
        .select("id, full_name, avatar_url, specialty")
        .eq("id", data.organizer_id)
        .maybeSingle();

      // Get registration count
      const { count } = await supabase
        .from("event_registrations")
        .select("*", { count: "exact", head: true })
        .eq("event_id", eventId)
        .eq("status", "confirmed");

      return {
        ...data,
        organizer,
        registrations_count: count || 0,
      } as Event & { organizer: { specialty?: string } };
    },
    enabled: !!eventId,
  });
};

export const useMyRegistrations = () => {
  return useQuery({
    queryKey: ["my-registrations"],
    queryFn: async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return [];

      const { data, error } = await supabase
        .from("event_registrations")
        .select("*")
        .eq("user_id", user.id)
        .order("registered_at", { ascending: false });

      if (error) throw error;

      // Fetch event details
      const eventIds = [...new Set((data || []).map(r => r.event_id))];
      const { data: events } = await supabase
        .from("events")
        .select("*")
        .in("id", eventIds);

      const eventsMap = new Map((events || []).map(e => [e.id, e]));

      return (data || []).map(reg => ({
        ...reg,
        event: eventsMap.get(reg.event_id),
      })) as EventRegistration[];
    },
  });
};

export const useUserRegistrationForEvent = (eventId: string) => {
  return useQuery({
    queryKey: ["registration", eventId],
    queryFn: async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return null;

      const { data, error } = await supabase
        .from("event_registrations")
        .select("*")
        .eq("event_id", eventId)
        .eq("user_id", user.id)
        .maybeSingle();

      if (error) throw error;
      return data as EventRegistration | null;
    },
    enabled: !!eventId,
  });
};